services:
  lso-client:
    image: lso-client
    network_mode: "host"
    depends_on:
      - lso-server
    build:
      context: LSO-client
    secrets:
      - openai_api_key
    environment:
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
      - ROBOT_ADDRESS=${ROBOT_ADDRESS}
      - SERVER_ADDRESS=${SERVER_ADDRESS}

  lso-server:
    image: lso-server
    ports:
      - 9999:9999
    build:
      context: LSO-server

secrets:
  openai_api_key:
    file: openai_api_key.txt