services:
  lso-client:
    image: lso-client
    depends_on:
      - lso-server
#      - furhat-sdk
    build:
      context: LSO-client
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  lso-server:
    image: lso-server
    ports:
      - 9999:9999
    build:
      context: LSO-server
      
# Per containerizzare l'SDK di Furhat, è necessario rendere visibile il microfono nel container

#  furhat-sdk:
#    image: furhat-sdk
#    ports:
#      - 1932:1932
#      - 8888:8888
#      - 8080:8080
#    build:
#      context: Furhat-SDK
